#!/usr/bin/env python
import os
import sys

env = SConscript("../godot-cpp/SConstruct")

env.Replace(CPPDEFINES=["DUEL_ENGINE_EXPORT"])

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
	library = env.SharedLibrary(
		"demo/bin/libduelengine.{}.{}.framework/libduelengine.{}.{}".format(
			env["platform"], env["target"], env["platform"], env["target"]
		),
		source=sources,
	)
else:
	library = env.SharedLibrary(
		"demo/bin/libduelengine{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
		source=sources,
	)

Default(library)
